first_number = 5
second_number = 2
print(f"{first_number} + {second_number} = {first_number + second_number}")
print(f"{first_number} - {second_number} = {first_number - second_number}")
print(f"{first_number} / {second_number} = {first_number / second_number}")
print(f"{first_number} x {second_number} = {first_number * second_number}")
print(f"{first_number} % {second_number} = {first_number % second_number}")
print(f"{first_number} // {second_number} = {first_number // second_number}")
print(f"{first_number} ** {second_number} = {first_number ** second_number}")